version: "3.8"
services:

  # PHP service
  app:
    build: .
    container_name: php-app
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - app-network

  # PhpMyAdmin service for mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge